### ISSUE TITLE
Disposable iterators and `for`-loops

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#10]
[Proposal](https://github.com/Kotlin/kotlin-coroutines/blob/master/disposable-iterators.md)

> A lazy sequence generated with `yield` may easily be iterating over a file or other resource that needs explicit disposal. Should we support C#-style translation of `for`-loops?

**Comment by ilya-g** [comment]
It becomes totally nondeterminate whether the disposal would be invoked. Consider consumers who don't know that finally block with dynamic check is required, for example those compiled with Kotlin 1.0

**Comment by abreslav** [comment]
"Totally nondeterminate" may be a bit of an overstatement, I think, but I see your point. The question is: what could we do to improve on this?

**Comment by voddan** [comment]
The motivation for the proposal is not clear. In particular, which problem is it going to solve: a) developers writing the boilerplate `finally` blocks manually or b) developers forgetting to write the checks?  Because the first seems like not that much of code, while the second one is made worse by supporting only `for` loops (which adds inconsistency)

**Comment by orangy** [comment]
Clients in Java code using Iterables produced by Kotlin will not know to call the function.

**Comment by orangy** [comment]
Even more important would be that you generally can't pass such an Iterable to any other (Java) library. Which kind of makes the whole proposal very fragile.

**Comment by Takhion** [comment]
What if instead of a "normal" `for` it was a special syntax (like `for disposing` or something), in order to:
1) solve the compatibility problem
2) avoid generating extra bytecode unless explicitly requested

**Comment by orangy** [comment]
> `for disposing`
You get a normal `Iterable<T>` from the coroutine function, and after you pass it somewhere as a parameter you don't have any clue if you need disposable for or not.

**Comment by cypressious** [comment]
Why do we need the extra interface if there is `Closable`?

**Comment by ilya-g** [comment]
@cypressious I have the same question, how `Disposable` relates to `Closeable`/`AutoCloseble` interfaces?

I suppose there are several points here:
- `Closeable` is mostly for IO-bound entities like input/output streams and readers, and `AutoCloseable` is more generic, for example it's implemented by Java 8 streams, so `Disposable` is closer to `AutoCloseable`.
- `Closeable` and `AutoCloseable` are java interfaces and missing in JS
- `AutoCloseable` is missing in JDK6

**Comment by cypressious** [comment]
Isn't disposing of resources typically the caller's responsibility? Let's assume I have a file and a function that reads it in a special way while `yield`ing items. What's wrong with the following approach:

```kotlin
file.use {
    for (item in it.generateFromFile()) {
    }
} // file is closed here
```

**Comment by mikehearn** [comment]
Isn't this what finalizers are for? Yes yes, I know finalizers are evil because they might never run if there is never a GC of that object, boo hiss, but ... as noted ... this proposal has exactly the same issue: sometimes the disposer/finaliser won't run depending on how it's used! And I'd think that for most resources, process termination should result in automatic cleanup anyway, because it's always possible for a process to be randomly killed due to a VM segfault or OOM condition or sudden power outage, thus a usable resource must be able to handle that, and clean process exit can always be handled by registering a shutdown hook.

So if I was writing an iterator that could iterate over a file or a socket or something, and I wanted this to work properly, I'd be tempted to just implement AutoClosable, close when the end was reached, and then register a finalizer to close in the other cases where the user forgets to do so.

**Comment by abreslav** [comment]
@mikehearn Finalizers are evil also because they slow things down.

**Comment by mikehearn** [comment]
That's certainly true, however in Java you pay those costs anyway, as platform classes that wrap the type of resources you usually want to cleanly close have finalizers anyway. This is the case for files, sockets, and a whole lot more if you grep the JDK sources.

You can do a much higher performance equivalent to finalization using phantom references and explicitly nulling them when closing is done properly, if for some reason these resources that must be closed as so frequent. But that requires you to use your own cleanup threads, so, probably best not to have it in the runtime.

**Comment by dzharkov** [comment]
It's been decided to postpone the feature because of Java interoperability issues described above
