### ISSUE TITLE
Can we optimize the case when no suspension is really needed?

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#26]
C# checks whether a task is already completed, and does not suspend if it is

**Comment by elizarov** [comment]
The current implementation of `suspendCoroutine` makes this check, so the trivial implementation of `CompletableFuture.await()` on top of `suspendCoroutine` works exactly like that -- it does not suspend coroutine when the future had already completed. This issues can be closed.

**Comment by ilya-g** [comment]
A part of performance is lost due to dumping stack into an object and then reading it back. 

In case if suspend function doesn't call continuation itself, but returns an indicator of whether suspension is going to happen or not, we could defer stack spilling until it's clear that we're going to suspend.

Even if we're not doing this optimization now, we should evaluate whether our design is future-proof enough to make it possible later.

**Comment by elizarov** [comment]
Closed. Obsolete.
