### ISSUE TITLE
Support for restarting a coroutine

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#29]
We could have something like a `reset()` function available on a state machine, to be able to support
- repeating the body of a coroutine multiple times without re-creating it
- implementing break/continue

**Comment by elizarov** [comment]
We have to have strong use-cases from this kind of `reset` method since it is inherently non thread-safe and is easy to mess up even in a single threaded case. The current approach allow to create new instances of state-machine as many times as needed and let the JIT take care about scalarization of newly allocated instances of state-machine whenever this is possible.

**Comment by elizarov** [comment]
Fill not fix. It seems just utterly easier to create a fresh instance when needed. Closed.
