### ISSUE TITLE
Why not use operator invoke instead of resume()/entryPoint()

### ISSUE THREAD

**Issue by mikehearn** [Kotlin/kotlin-coroutines#33]
Seems like this is the kind of thing operator invoke was born for.

**Comment by abreslav** [comment]
`resume` and `entryPoint` are rather different: and having no name for the latter looks weird to me.

And if we turn both into `invoke`, the resulting code will look like this:

```
fun <T> async(coroutine c: () -> Coroutine<AsyncController<T>>): ... {
    ...
    c()(controller)(Unit)
    ...
}
```

Which is far from self-explanatory, compared to `c().entryPoint(controller).resume(Unit)`.

I don't think that DSL-izing coroutine APIs makes much sense, because it is not intended to be used by client code, and what library code will be using it is more likely to benefit from clear naming than from slightly shorter syntax.

**Comment by mikehearn** [comment]
Fair enough then.
