### ISSUE TITLE
Integrate with Quasar?

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#41]
[Quasar](http://docs.paralleluniverse.co/quasar/)'s approach to asynchronous computations is more general than ours: it allows suspending calls from methods several stack frames below the coroutine. This requires some extra runtime work, but can be very convenient.

Question: can we (optionally) integrate with Quasar?

This would require us to handle Quasar's `@Suspendable` calls as suspension points, and probably require a compiler plugin or something similar.

Incremental compilation may also be a challenge

**Comment by abreslav** [comment]
What can be checked statically:
- fiber-blocking APIs must be called from a `@Suspendable` function only
  - are such APIs always annotated accordingly?

What, apparently, can't be checked statically:
- every call that eventually fiber-blocks, is called from an appropriate context (that supports resumption)

**Comment by mikehearn** [comment]
Once Java 9 is out, I guess some Quasar-using code won't use annotations any more. They're kind of a pain to be honest. It's easy to miss one by accident.

**Comment by abreslav** [comment]
Without annotations it's all left to runtime magic, which I'm afraid, may scare off many users. 
But maybe the whole point is that what such users want is no annotations and entirely dynamic behavior of this feature?

**Comment by pron** [comment]
> Without annotations it's all left to runtime magic, which I'm afraid, may scare off many users. 

I agree that this is a real concern, although personally I find it a bit ironic, as all of HotSpot is based around "runtime magic". Pretty much everything HotSpot does is generate machine code on the fly, and then re-generate it again. :)

**Comment by mikehearn** [comment]
Well, in my view it actually reduces the amount of runtime magic. Here's how Quasar works today, briefly:

- A JVMTI agent intercepts every class load request, finds all suspendable methods and rewrites them so whenever they put something on the real JVM stack, they also push them onto a shadow fiber stack.
- When suspension occurs, this stack is stored, the real stack is unwound with an exception
- On resume, the rewritten code skips to the right place in the state machine, reloading things from the fiber stack

That's a lot of magic that can go wrong. In Java 9 the JVM exposes the contents of the actual VM stack to user code. So the magic is now like this:

- There is no longer any need to intercept and scan every single loaded class. This is a performance win.
- There is no longer any need for fibers to push things onto a shadow stack. This is also a performance win.
- When a suspension point is hit, the engine can walk the stack and locate any uninstrumented methods, then in collaboration with the JVMTI agent, rewrite them to only contain the resume code. The suspended fiber contains the stack variables as provided by the JVM.

At least, that's my understanding of it. So it's not just a convenience thing where annotations are awkward, it's actually a performance win and the rewritten bytecode is simpler too. It relies on the fact that the JVM will happily let you rewrite method bytecode on the fly and swap it in to a running program. Now that really is magic :-)

**Comment by abreslav** [comment]
> There is no longer any need for fibers to push things onto a shadow stack. This is also a performance win.

@pron Can this really be so?

**Comment by mikehearn** [comment]
I should note here an important caveat: support for accessing the stack variables is currently exposed only in HotSpot 9 and only via a HotSpot specific API. It's not currently targeted to be a part of the standard Java SE platform, as far as I'm aware (unsure why not).

**Comment by pron** [comment]
Not quite :)

First, Quasar does not make use of a JVMTI agent but a plain Java agent (it's just a plain Java library).

With the stack-walker API the there would still be pushing to the shadow stack in transformed methods for two reasons: 1/ the API does not help with *restoring* the values, and 2/ the instrumented code is (currently) much faster than the stack-walker. The plan is to use the stack-walker only the first time a method is blocked, but we'll experiment more. Things are in flux.

We have [this JMH benchmark](https://github.com/puniverse/quasar/blob/master/quasar-core/src/jmh/java/co/paralleluniverse/fibers/FiberOverheadJMHBenchmark.java) that tests the instrumentation overhead. Feel free to try it.

@mikehearn 

> unsure why not

Because it's still experimental and basically meant as a testing bed for fibers, with the intention of natively supporting fibers on the JVM in the future

**Comment by Groostav** [comment]
Alright so I think I've got enough information to make a useful contribution here:

My use case is elaborated [on stackoverflow here](http://stackoverflow.com/questions/39755964/is-the-callstack-a-language-safe-data-structure-quasar-fortran).

Specifically this would require this [kotlin code](https://gist.github.com/Groostav/f2b81d567bd85f2c904c5ed395220fd3): and support for stackful-coroutines. Given that Kotlin has made the executive decision not to support stack-ful co-routines (for perfectly valid reasons), integration with Quasar would be a nice addition for me as it would allow me to write ~idiomatic kotlin instead of Quasar-dependant kotlin.

**Comment by abreslav** [comment]
@Groostav when depending on Quasar integration, you'll still be writing Quasar-dependent Kotlin

**Comment by elizarov** [comment]
With the revised coroutines in implementation in 1.1-M04 the stack-full coroutines in Kotlin are around the corner (you can already do them with just a simple helper function). 

Having said, there is a lot of value in Quasar integration, because Quasar works with Java code. Quasar integration would let users to seamlessly combine Kotlin suspending functions with Java `@Suspendable` methods in Quasar. 

We'll need an adapter from one world to another and back. However, as I see it, that will need an introduction of an additional abstraction into Quasar core. In particular, one would need to extract a suspendable runnable interface from Quasar's Fiber class:

```java
interface SuspendableRunnable {
    void run() throws SuspnendExecution
}
```

With this kind of interface in hand, one can define a helper function to call suspenedable Java code that was instrumented by Quasar from a Kotlin suspending function:

```
suspend operator fun SuspendableRunnable.invoke()
```

The implementation, that would necessarily have to use Quasar internals (and will not instrumented by Quasar itself), would catch Quasar's `SuspendExecution ` and transform the suspension to the Kotlin's CPS convention (return SUSPNEDED token when the execution was suspended)

The inverse transformation to allow calls from Java suspendable method to Kotlin's suspending functions would need the adapter like this:

```
@Throws(SuspendExecution::class)
fun <T> suspending(block: suspend () -> T): T
```

That would adapt Kotlin's CPS transformation to Quasar's convention of throwing `SuspendExecution` exception on suspension. Note, that this `suspending` function would have to be excluded from bytecode transformation by Quasar, but other functions invoking this function will be transformed by Quasar as usual.

**Comment by pron** [comment]
This branch of Quasar contains a [`Continuation`](https://github.com/puniverse/quasar/blob/cont2/quasar-core/src/main/java/co/paralleluniverse/fibers/Continuation.java) class. We weren't planning to merge it into master until Java 9, which would hopefully make all annotations redundant, but something could be done for Kotlin. Quasar's continuation class is quite sophisticated, implementing what I call [scoped continuations](http://blog.paralleluniverse.co/2015/08/07/scoped-continuations/), and is sometimes referred to in the literature as "delimited continuations with multiple named prompts", but doing something simpler is certainly possible.

P.S.

While I'm glad Kotlin is adopting delimited continuations (over stackless), experience shows that even that is not the best user-facing abstraction, and fibers (i.e., scheduled continuations) is the best way to integrate continuations into a language. It gives you 99% of the benefit for the simplest API possible. Exposing continuations directly, while sometimes useful (generators, nondeterminism), results in people doing things that are often too clever for their own good.

**Comment by unicomp21** [comment]
Too bad we don't have UMS (user mode scheduling) for linux.

**Comment by elizarov** [comment]
Integration with Quasar is now available in kotlinx.coroutines version 0.18. See https://github.com/Kotlin/kotlinx.coroutines/tree/0.18/integration/kotlinx-coroutines-quasar
