### ISSUE TITLE
Monadic do notation (requires continuations that can be called multiple times)

### ISSUE THREAD

**Issue by h0tk3y** [Kotlin/kotlin-coroutines#72]
I'm trying to get close to the _Haskell do notation_ for [my monads implementation attempt](https://github.com/h0tk3y/kotlin-monads.git). 

In Haskell, a _do_ block is translated into nested `>>=` calls, like this:

    m = do
        x <- [1, 2, 3]
        y <- [x, x]
        [y, y + 1]

    // translated into:

    m = [1, 2, 3] >>= x -> // f
        [x, x] >>= y -> // g
            [y, y+1]

Here, `m` results into `[1, 2, 1, 2, 2, 3, 2, 3, 3, 4, 3, 4]`. Note that it's the `>>=` implementation that decides how to (and whether to) call `f` and `g`. In this example, `f` is called 3 times, and `g` is called twice each time.

In Kotlin, the coroutine transformation can be used to do almost the same: we can pass the `Continuation<T>` into the `bind` implementation, so that it calls the continuation.

    val m = doWith(monadListOf(0)) {
        val x = bind(monadListOf(1, 2, 3))
        val y = bind(monadListOf(x, x))
        then(monadListOf(y, y + 1))
    } as MonadList

    println(m) // MonadList(list=[1, 2, 1, 2, 2, 3, 2, 3, 3, 4, 3, 4])

But several problems arise:

* A `Continuation<T>` implemented by a state machine modifies its `label`, so that we cannot run one continuation several times from the same `label`. _The workaround I used: back up the `label` through reflection before the `resume` call and restore it once the call returns._

* If there are mutable variables declared inside the coroutine block, their state is naturally shared between the runs of the continuation. Example:

        val m = doWith(monadListOf(0)) {
            for (i in 1..10)
                then(monadListOf(0, 0))
        } as MonadList

        println(m) // MonadList(list=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
        // not 1024 items as one would expect, because of `i` shared between the runs

     Neither prohibiting `var`s in such a coroutine nor defensive copying of the `var`s seems to solve the problem: a continuation can still use and mutate state from somewhere else.

**Comment by h0tk3y** [comment]
Also, this coroutines use case contradicts the semantics described in #69:

> They cannot call other suspension functions multiple times and they should not do anything after another suspension function was called.

**Comment by dzharkov** [comment]
Please clarify, why do you need multiple suspension calls inside another suspend function

**Comment by elizarov** [comment]
Let's me clarify a bit the source of seeming contradictions. Functional languages, like Haskell and Scheme, provide full-blown unrestricted continuations that can be called multiple times due to a combination of their ubiquitous tail-call support and mostly value semantics (they have no or minimal mutable state)

Kotlin provides only scoped/limited continuations purely for pragmatic reasons, due to the need for efficient implementation of various common control patterns. Fortunately, most things that you can implement on top of unrestricted continuations (like either monad, throw monad, etc) already exist in Kotlin as first-class standalone features with _native_ implementation or can be implemented directly and efficiently using other idiomatic Kotlin concepts. 

For example, you give a piece of Haskel code that is using `do` syntax with list monad to implement list comprehensions. It can be _natively_ implemented in Kotlin. It is quite a trivial exercise to do  _list comprehensions_ in Kotlin by defining a special `list` coroutine builder for that, so that your Haskell code 

```
m = do
    x <- [1, 2, 3]
    y <- [x, x]
    [y, y + 1]
```

can be _directly_ translated into Kotlin, while enjoying extremely efficient execution:

```
val m = list {
    for (x in listOf(1, 2, 3))
    for (y in listOf(x, x))
    yield Pair(y, y + 1)
}
```

**Comment by elizarov** [comment]
Let me add that you don't even need coroutines for that. See https://youtrack.jetbrains.com/issue/KT-15363 which will let you write:

```
val m = buildList {
    for (x in listOf(1, 2, 3))
    for (y in listOf(x, x))
    add(Pair(y, y + 1))
}
```

**Comment by h0tk3y** [comment]
I agree to all the above, but, of course, this use case covers generic *do notation* for arbitrary monads,  while the `MonadList` is just an example.

**Comment by elizarov** [comment]
So, what is your _actual_ use-case for _do nation_? What monad you'd like to be able to represent with it? Can you give a corresponding Haskell code, for example?

**Comment by h0tk3y** [comment]
The actual use case is implementing generic monads in a library that would allow user monad types along with the bundled ones. The *do notation* would be used interchangeably with any monadic type the user provides. 

Here's a (quite synthetic) example of a function that would work with arbitrary monad in Haskell with *do notation*:

```haskell
genericMonadFlow :: Monad m => m Int -> (Int -> m Int) -> (Int -> m Int) -> m Int
genericMonadFlow m ifGood ifBad = do
    x <- m
    y <- (if x `mod` 2 == 0 then ifGood else ifBad) x
    (if y > 0 then ifGood else ifBad) y
```

And its equivalent in Kotlin:

```kotlin
fun <M : Monad<M, *>> genericMonadFlow(m: Monad<M, Int>,
                                       ifGood: Return<M>.(Int) -> Monad<M, Int>,
                                       ifBad: Return<M>.(Int) -> Monad<M, Int>) = doWith(m) {
    val y = bind((if (value % 2 == 0) ifGood else ifBad)(value))
    then((if (y > 0) ifGood else ifBad)(y))
}
```
(this example works with [`kotlin-monads`](https://github.com/h0tk3y/kotlin-monads))

And its usage for three different monad types:

```kotlin
val forList = genericMonadFlow(monadListOf(1, 2), { monadListOf(it, it + 1) }, { monadListOf(-it) })
val forMaybe = genericMonadFlow(just(2), { just(it + 1) }, { just(it - 1) })
val forWriter = genericMonadFlow(Writer(0, ""), { Writer(it + 1, "$it is good ") }, { returns(it - 1) })
println(forList) // MonadList(list=[1, 2, 3, 3, 4, 1, 2, 3, 3, 4])
println(forMaybe) // Just 4
println(forWriter) // Writer(result=2, log=0 is good 1 is good )
```

Not sure if the example demonstrates that correctly, but the purpose is to provide a way to separate the computations binding logic from the computations, i.e. exactly what monads are.

**Comment by windoze** [comment]
I don't quite understand the question, why do we need monad in kotlin? More specifically, why do we need do notation in an imperative language? We can run code in sequence without any special constructs:
```
statement1
statement2
statement3
```
What is the benefit to wrap them in a do block?

AFAIK monad is just a method to resolve some particular problems introduced by pure functional languages, i.e. running code in sequence or handling side effects, but kotlin has never been a pure functional language since day one.

So I guess we never really need this until one day kotlin has a FPGA backend.

**Comment by Baughn** [comment]
> AFAIK monad is just a method to resolve some particular problems introduced by pure functional languages, i.e. running code in sequence or handling side effects, but kotlin has never been a pure functional language since day one.

That's not entirely true. Monads were invented for that purpose, yes, but they turned out to be more broadly applicable. Probably the easiest-to-explain variant, although still incomplete, would be to say that they're environments—the simplest examples of which would be the reader/writer monads and of course Parsec.

There's some overlap with what you can do with objects, but not 100%. Unfortunately it's pretty hard to explain.

**Comment by dtchepak** [comment]
Hi @elizarov ,

Sorry this is a little off-topic, but I came across this issue looking for information on using `Either`/`Result` type in Kotlin, so hopefully this may also be relevant to others that also find this issue. 

In [your previous comment](https://github.com/Kotlin/kotlin-coroutines/issues/72#issuecomment-264416933) you mention things like `Either` "... already exist in Kotlin as first-class standalone features with native implementation or can be implemented directly and efficiently using other idiomatic Kotlin concepts". Could you please explain/link to how this is done?

My specific use case is trying to parse some JSON using a `Result<E,T>` type (similar to F#'s [`Result`](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/results) or Haskell's `Either` type). I ended up with code that looks something like:

```kotlin
 fun deserialise(json: JsonElement): Result<JsonError, Person> {
                return json.getJsonObject().flatMap { jobj ->
                    jobj.lookupString("Name").flatMap { name ->
                        jobj.lookupString("Email").flatMap { email ->
                            jobj.lookupDate("Dob").flatMap { dob ->
                                Success<JsonError, Person>(Person(name, email, dob))
                                }}}}
}
```

To reduce this nesting I needed to switch to modelling this as `Pair<T, JsonError?>`:

```kotlin
    val (name, nameError) = jobj.lookupString2("Name")
    if (nameError != null) return fail(null, nameError)
    val (email, emailError) = jobj.lookupString2("Email")
    if (emailError != null) return fail(null, emailError)
    val (dob, dobError) = jobj.lookupDate2("Dob")
    if (dobError != null) return fail(null, dobError)
    return succeed(Person(name, email, dob))
```

This relies on error-prone manual checking of error values before accessing the first item of the pair, and (like the `flatMap` version) becomes more unwieldy as we increase the number of arguments/lookups.

The equivalent with do-notation would look something like:

```
 fun deserialise(json: JsonElement): Result<JsonError, Person> {
    return result {
          val jobj <- json.getJsonObject()
          val name <- json.lookupString("Name")
          val email <- json.lookupString("Email")
          val dob <- json.lookupDate("Dob")
          Success<JsonError, Person>(Person(name, email, dob))
    }
}
```

Using nullables instead of `Result` gives much neater parsing code, but means I lose the specifics of errors that occur. Resorting to traditional exceptions also provides neater code, but for this particular code I need to avoid `try/catch` for this.

I'm not sure if I should look at hijacking coroutines for this, or if there is a better way to achieve this using idiomatic Kotlin.

**Comment by elizarov** [comment]
Every Kotlin function _either_ returns a result or throws an exception, so, in effect, the actual return type of every Kotlin's function "returning" `T` is `Either<Throwable, T>`. Moreover, semantics of execution in the body of Kotlin functions are defined in such a way as to model `do` notation on `Either` monad. The idiomatic Kotlin way to write your `deserialize` function is:

```
fun deserialise(json: JsonElement): Person { // actual result is Either<Throwable, Person>
   val jobj = json.getJsonObject()
   val name = json.lookupString("Name")
   val email =  json.lookupString("Email")
   val dob = json.lookupDate("Dob")
   return Person(name, email, dob)
}
```

> Notice its striking similarity with `do` notation (the only notable difference is that `<-` is replaced with `=`). That is so by design, because it _is_ a do notation over `Either` monad.

The code above assumes that `getJsonObject` and `lookupXXX` are Kolinified in the same way, e.g. their return type is changed from `Either<SomeError, T>` to just `T`.

**Comment by dtchepak** [comment]
Thanks for the reply, it makes perfect sense. Unfortunately in this case I need to avoid `try/catch` in the calling code, so I think I'm stuck with a non-idiomatic approach.

**Comment by elizarov** [comment]
If you have an existing non-idiomatic code that expect some kind of `Result` type, then I'd suggest to write a helper function to convert idiomatic Kotlin invocation into results. Something like this (modify it suit your needs):

```
inline fun <T> resultOf(block: () -> T): Result<T> = 
    try { Result.Success(block()) }
    catch (e: Throwable) { Result.Failure(e) }
````

This way you can write `resultOf { deserialize(json) }`anywhere you need it without having to use `try/catch` anymore.
