### ISSUE TITLE
Type of `::await` inside a coroutine

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#8]
Since the continuation parameter is passed implicitly, and is not easily retrieved by the coroutine code, what type should be given to `::await`?

**Comment by elizarov** [comment]
Its type is naturally `suspend (Future<T>) -> T`

**Comment by dzharkov** [comment]
Is `suspend (Future<T>) -> T` coercible to `(Future<T>) -> T`?
If the answer is no, then we loose ability to use it somehow like `futures.map(::await)`, that I see
as a very nice use case.

If yes, then the coercion should be restricted to an argument of an inline function in a coroutine.
Otherwise, the suspension cannot be handled properly (see https://github.com/Kotlin/kotlin-coroutines/issues/48).
Outside of coroutines, the coercion should be prohibited.

Note that currently, we have no syntax ability to use modifiers with functional types (annotations only).

**Comment by elizarov** [comment]
The answer is a definite no. The subtyping relations goes the other way around `(Future<T>) -> T` is a subtype of `suspend (Future<T>) -> T`, because the later can suspend or continue execution, when the former is more restricted (does not have the choice to suspend). 

This works nicely to _prevent_ things like `futures.map(::await)`, because they would horribly fail is they were allowed due to multiple calls to the same continuation. Unfortunately (or fortunately?) `suspend` is a viral modifier. You have to have a separate suspend function `futures.mapAwait` (?) 

We don't have to support any of that in 1.1 at all. We can always introduce proper subtyping relations later. I think it is Ok to forbid `::await` for now, until we can imbue it with an appropriate type.

**Comment by dzharkov** [comment]
What's the problem with multiple calls? 
They all will be inlined into the coroutine as common subsequent suspend calls.

I agree with your arguments, but I always find it clumsy when `map { it.await() }` is allowed, but `map(::await)` isn't, while for me these notations should have similar semantic.

**Comment by elizarov** [comment]
Good point. It shall be allowed for `inline` functions inside coroutines. That's actually a really cool feature. You shall be able to use it inside coroutine, but not in a tail call of other suspend functions.

**Comment by abreslav** [comment]
I'd like to point out that we have an option to prohibit `::await` in 1.1

**Comment by elizarov** [comment]
Closed. Obsolete.
