### ISSUE TITLE
Alternative naming for `generate-yeild`

### ISSUE THREAD

**Issue by voddan** [Kotlin/kotlin-coroutines#81]
I don't feel that `generate { yeild }` naming is clear enough. In particular, there is no indication that this is a way to construct a `Sequence`.

I propose renaming this constructs into `sequence { yeild }`. That way it becomes just another factory method for creating sequences.

In addition we can have `list {yeild}`, which would be the eager version of it (can be done without coroutines). Also I thought about `iterator {yeild}`, but I think it doesn't read well.

**Comment by elizarov** [comment]
The `sequence`/`yield` naming is an interesting and appealing idea. I'm not positive on the `list`/`yield`, though, because it does not actually need coroutines and should not use `yield` verb at all (which implies control transfer between coroutines). Moreover, there is a request to add `buildList`/`add` pair to stdlib: https://youtrack.jetbrains.com/issue/KT-15363

**Comment by elizarov** [comment]
The resolution was to name it `buildSequence`
