### ISSUE TITLE
Why no explicit syntax denoting a suspension point?

### ISSUE THREAD

**Issue by jakeswenson** [Kotlin/kotlin-coroutines#89]
I've been getting to play with kotlin a bit, and i love the language. I started reading up on the coroutine work thats going on here, and it's great stuff. 

My only concern that the suspension points are not clear when reading code. Going through the examples it was hard to understand that the call to `aRead` creates a suspension point.

What was the reason for not having some syntax signaling the reader this is happening?
I'm looking for some of the insight and discussion about not adding some syntax to demarcate continuations and suspension points.

Coming from C# and F# I love the explicit syntax for creating a suspension point. (`await` from C# or the bang `!` syntax of F#) 

I understand the language syntax for coroutines is "not likely to change at this point" so i guess i'm too late to make any valuable contributions to the discussion... but I can't help but feel like this hurts the reader.

**Comment by jakeswenson** [comment]
Oh goodness. I just noticed that most of the 'async' suspension functions are going to be signaled with a single `a` before each method? 😱 
Is this also the recommended guidance for naming suspension functions?

**Comment by elizarov** [comment]
No guidance yet. The naming in `kotlinx-coroutines-nio` module is _not_ an example to follow.

We are still experimenting with different namings. The best approach we've found so far, is _not_ combine suspending functions and other types of async functions under the same interfaces. These extension functions to NIO `AsyncXXX` interfaces that you mention are basically a short-term band-aid. We still don't have an implementation of truly suspending IO streams with suspending read/write functions (nobody wrote them yet).

You can take a look at channels, for example: https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#channels
The just have suspending `send` and `receive` and it works pretty well for them, because channels are designed for coroutine communication, hence they don't have any blocking functions, nor any functions with callbacks, thus there is no confusion. You are writing suspending code when you are using channels.

**Comment by jakeswenson** [comment]
Firstly, phew! _Thanks_ for the clarification that the naming guidance isn't set yet. What is the Difference between the functions that are currently in the NIO package and what you want? If I understand correctly you want some adapter/facade type to expose only suspendible/async functions? I'd love to help just trying to make sure i understand what to do 😄 
 
Secondly, while i completely agree the channels interaction is seamless and smooth, my concern about not having something in the language the signals when where suspension points are will make grok'ing and providing useful advice during pull requests and code reviews harder.

**What was the reasoning behind not having some explicit syntax where a suspension will occur?** In the languages that i know they all have some special signal for this be it `await` in typescript/python/c# or `!` in f# or the `<-` from go.

**Comment by jakeswenson** [comment]
@snrostov Thanks thats it. I'll close as a duplicate
